### ISSUE TITLE
Share types between backend and frontend (`Product`, etc)

### ISSUE THREAD

**Issue by silicakes** [electricmonk/ts-react-tdd#14]
Share types between backend and frontend (`Product`, etc)

Add support for yarn workspaces

_Originally posted by @electricmonk in https://github.com/electricmonk/ts-react-tdd/issues/4#issuecomment-1053576792_

**Comment by electricmonk** [comment]
What's the difference between yarn workspaces and Lerna?

**Comment by silicakes** [comment]
> so Lerna makes use of Yarn workspaces?
> 
> I see that you already used the `import Foo from @ts-react-tdd/client` syntax in #15. What's left to do in this issue?

1. Correct, you can see it under lerna's config (`useWorkspaces: true`)
2. Closing the issue.
